### ISSUE TITLE
Tests not running with PHPUnit 6 

### ISSUE THREAD

**Issue by editionslva** [Raphhh/samurai#5]
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found when running tests with PHPunit v6

**Comment by Raphhh** [comment]
"@stable" version in the composer.json should be changed.

**Comment by editionslva** [comment]
En effet c'est une solution plus rapide mais je voulais proposer une solution plus pérenne  mais visiblement le pull request n'a pas passé la barrière Travis à cause de la config PHP 7

**Comment by Raphhh** [comment]
I do not understand how you get PHPUnit 6? When I install the project, everything seems to be ok: it is PHPUnit 4.

**Comment by Raphhh** [comment]
Build is ok: https://travis-ci.org/Raphhh/samurai/builds/212200201

**Comment by editionslva** [comment]
Bonjour,

En fait après clonage sur local et composer update, il récupère la dernière version stable comme indiqué dans le json.

Par contre je lance bien /vendor/phpunit/phpunit/phpunit tests  et non phpunit tests (au cas où il y aurait une vieille version de php unit installée en global dans composer etqui serait lancée  en utilisant le PATH)

**Comment by Raphhh** [comment]
1/If you want to develop the project (and not install it globally), after git clone, you should run "$ composer install" and not "$ composer update".

2/ Indeed, to run PHPUnit, you should run "$ vendor/bin/phpunit" (which comes from vendor/phpunit/phpunit/phpunit)

**Comment by editionslva** [comment]
Thank you for the clarification.
